server:
  port: 7300

ch:
  user:
#     endpoint: http://user-dd-service:7211/ch-user-dd
    endpoint: http://user-dd-service.tootest.svc.cluster.local:7211/ch-user-dd
    


logging:
  pattern:
    level: 'TOOXX [%X{dd.trace_id}/%X{dd.span_id}] TOOXX'
