apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-dd-deployment
  namespace: {NAMESPACE}
  labels:
    app: bff-dd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff-dd
  template:
    metadata:
      annotations:
        k8s.aliyun.com/acr-instance-id: cri-3fynibeigjxpi5o6
        k8s.oneconnect.xom.cn/datadog-java: 'true'
      labels:
        app: bff-dd
        tags.datadoghq.com/env: occ-tootest
        tags.datadoghq.com/occ-service-domain: tootest
        tags.datadoghq.com/service: bff-dd
        tags.datadoghq.com/source: java
        tags.datadoghq.com/version: GITHUB_SHA
    spec:
      containers:
        - name: bff-dd
          image: xom-ecomm-acr02-registry.cn-shanghai.cr.aliyuncs.com/tootest/ch-bff-dd:GITHUB_SHA
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7300
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dd"
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: db-host
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user-password
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"

