apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-deployment
  namespace: {NAMESPACE}
  labels:
    app: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      annotations:
        k8s.aliyun.com/acr-instance-id: cri-3fynibeigjxpi5o6
        k8s.oneconnect.xom.cn/datadog-java: 'true'
      labels:
        app: bff
        tags.datadoghq.com/env: occ-tootest
        tags.datadoghq.com/occ-service-domain: tootest
        tags.datadoghq.com/service: bff-dd
        tags.datadoghq.com/source: java
        tags.datadoghq.com/version: GITHUB_SHA
    spec:
      containers:
        - name: bff
          image: xom-ecomm-acr02-registry.cn-shanghai.cr.aliyuncs.com/tootest/ch-bff:GITHUB_SHA
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9300
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"

