apiVersion: v1
kind: Service
metadata:
  name: bff-dd-service
  namespace: {NAMESPACE}
  labels:
    app: bff-dd
spec:
  selector:
    app: bff-dd
  ports:
  - port: 7300
    protocol: TCP
    targetPort: 7300
  type: LoadBalancer


